### ISSUE TITLE
Auto-delete Users in nextcloud

### ISSUE THREAD

**Issue by Numifox** [QuITAC/nextcloud#11]
When a user is deleted in authentik they should also be deleted in nextcloud, e.g. by a cronjob

**Comment by DSMaVie** [comment]
I have recently discovered SCIM. That is a common interface for user provisioning. A quick search revealed that both NC and Authentik have possibilities to use SCIM in conjunction with OIDC.
We should investigate this further.

**Comment by mikitsu** [comment]
Authentik also supports webhooks (as event notifications).

**Comment by ghost** [comment]
@Numifox schaut sich an, wie sowas grundsätzlich implementiert wird
