### ISSUE TITLE
Test Passman as  PWManager Alternative

### ISSUE THREAD

**Issue by DSMaVie** [QuITAC/nextcloud#12]
NC Passwords cannot assign passwords to circles or groups. Only to users. That will be to much hassle.
How to we proceed? Do we scrub that feature?

**Comment by DSMaVie** [comment]
An alternative that shares credentials could be a keepassXC vault with a verbally shared password.

**Comment by DSMaVie** [comment]
we decided that @greedykangaroo01 checks if Passman is a valid alternative. If yes, they will install it if not, they will remove all passward managers from the system and we will deal with password management after the cloud is established.

**Comment by ghost** [comment]
Vaultwarden OIDC fork im Kopf haben
