### ISSUE TITLE
Discuss nextcloud talk limitations

### ISSUE THREAD

**Issue by lkbrdrstr** [QuITAC/nextcloud#13]

**Comment by DSMaVie** [comment]
we see the following limitations:
* no auto-join of users to their group/circle chats
* no threads, just answers to previous messages

we discuss the limiatations with the vorstand and the users and give them two options:
* move to talk dispite the limitations
* postpone the development of a chat component and stay with slack.

**Comment by DSMaVie** [comment]
The vorstand has favored the approach to postpone the chat component and work with slack until a better alternative can be established. Alternatively, they have proposed a mixed approach in which NC Talk can be used for peer-to-peer conversations but major digital discussions and announcement are done via Slack until a better system can be found. 
They will discuss this topic at the next plenum with the rest of ref.
