### ISSUE TITLE
Email Addresse raus aus Authentik nehmen

### ISSUE THREAD

**Issue by JIrgend** [QuITAC/nextcloud#7]
emails von allen stehen im kontaktbuch, evtl anbindung durch authentik falsch oder setting in nc anpassen

**Comment by JIrgend** [comment]
Authentik uid an nc uebergeben? und trulla bitte admin rechte geben

**Comment by JIrgend** [comment]
System Address Book is disabled. Email/User name is still exposes by button in upper right corner. 
Might not be solvable, solution idea: announce that authentik email address is exposed, if that is not ok ask for a xyz@queerreferat-aachen.de email address

**Comment by DSMaVie** [comment]
most of the vorstandsmitglieder favor the approach described in the previous comment, albeit some are not happy with that, however they can live with the solution to offer queerreferat-aachen.de mail adresses to those that do not want to expose their mail.
the alternative to try to hide with custom css was discussed and is not seen as an optimal solution.
they will discuss the options at the next plenum.

**Comment by Seppel3210** [comment]
An we thought about is to not require email verification so you can just input an invalid email address.

**Comment by NattCaat** [comment]
Anstatt invalide Email Addressen zu erlauben, nehmen wir das Feld für die Addresse einfach komplett raus. Wir müssen noch schauen, wie das technisch gemacht wird.

**Comment by NattCaat** [comment]
Eventuell Email-Addresse in Authentik speichern und Nextcloud keinen Zugriff darauf geben

**Comment by Numifox** [comment]
Haben nun rasugenommen das NC Email Adresse von OIDC anfragt und funktioniert :)
